"""
Pydantic models defining request and response shapes for the API.

These models document and validate the structure of data exchanged
between the client and server. Using Pydantic helps catch malformed
payloads early and produces clear error messages for API consumers.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class JobSettings(BaseModel):
    """Settings controlling how the mastering job will run."""

    preset: str = Field(
        default="hi_fi_streaming",
        title="Preset",
        description="Name of the mastering preset to apply.",
    )
    enable_demucs: bool = Field(
        default=False,
        title="Enable Demucs Separation",
        description=(
            "If True, perform stem separation using HT-Demucs before mastering. "
            "This allows the algorithm to treat vocals, bass and drums separately."
        ),
    )
    mono_sub: bool = Field(
        default=True,
        title="Mono Sub",
        description="Enable mono sub summing to improve low-frequency focus.",
    )
    dynamic_eq: bool = Field(
        default=True,
        title="Dynamic Masking EQ",
        description="Activate the adaptive low-mid dip based on masking ratio.",
    )
    target_lufs: Optional[float] = Field(
        default=None,
        title="Target LUFS",
        description=(
            "Desired integrated loudness (in LUFS). If unspecified, the script will pick "
            "a sensible target based on the preset and loudness governor."
        ),
    )


class JobCreateResponse(BaseModel):
    """Response returned when a job is created."""

    id: str = Field(..., title="Job ID")
    status: str = Field(..., title="Initial status")
    settings: JobSettings = Field(..., title="Echo of submitted settings")


class JobStatusResponse(BaseModel):
    """Representation of a running or finished job."""

    id: str = Field(..., title="Job ID")
    status: str = Field(..., title="Current status")
    progress: float = Field(..., title="Progress", ge=0.0, le=100.0)
    created_at: datetime = Field(..., title="Creation timestamp")
    started_at: Optional[datetime] = Field(None, title="Processing start timestamp")
    finished_at: Optional[datetime] = Field(None, title="Processing finished timestamp")
    error: Optional[str] = Field(None, title="Error message, if any")
    settings: JobSettings = Field(..., title="Echo of submitted settings")


class JobReportResponse(BaseModel):
    """Response containing the mastering report generated by the script."""

    report: Dict[str, Any] = Field(..., title="Arbitrary JSON report")


class ErrorResponse(BaseModel):
    """Standard error response shape."""

    detail: str = Field(..., title="Human-readable error message")
