"""
Pydantic models defining request and response shapes for the API.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class JobSettings(BaseModel):
    """Settings controlling how the mastering job will run."""

    preset: str = Field(default="hi_fi_streaming", description="Name of the mastering preset.")
    enable_demucs: Optional[bool] = Field(default=None, description="Toggle stem separation (Demucs).")
    mono_sub: Optional[bool] = Field(default=None, description="Toggle mono-anchor low frequencies below ~120 Hz.")
    dynamic_eq: Optional[bool] = Field(default=None, description="Toggle masking-aware dynamic EQ in the 200-500 Hz band.")
    truepeak_limiter: Optional[bool] = Field(default=None, description="Toggle the true-peak limiter + soft clip stage.")
    target_lufs: Optional[float] = Field(default=None, description="Desired integrated loudness estimate.")
    true_peak_ceiling: float = Field(default=-1.0, description="Limiter output ceiling in dBTP.")
    warmth: float = Field(default=0.0, ge=0.0, le=100.0, description="Analog-style warmth from 0 to 100%.")


class JobCreateResponse(BaseModel):
    """Response returned when a job is created."""

    id: str
    status: str
    settings: JobSettings


class JobStatusResponse(BaseModel):
    """Representation of a running or finished job."""

    id: str
    status: str
    progress: float = Field(..., ge=0.0, le=100.0)
    created_at: datetime
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    error: Optional[str] = None
    settings: JobSettings


class JobReportResponse(BaseModel):
    """Response containing the mastering report generated by the script."""

    report: Dict[str, Any]


class ErrorResponse(BaseModel):
    """Standard error response shape."""

    detail: str
